<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.59" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
    <PackageReference Include="SkiaSharp" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="4.151.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <None Update="SampleImages\Screenshot 2026-05-27 094239.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SampleImages\Screenshot_2019-01-25-23-51-29.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SampleImages\WeSnhQZ-sons-of-anarchy-wallpaper.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="SampleImages\wp1883550-shameless-wallpapers.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
